[build]
  command = "npm --workspace sales-dashboard-frontend run build"
  publish = "frontend/out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Disable the Next.js plugin to avoid static generation issues
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm --workspace sales-dashboard-frontend run dev"
  port = 3000
  publish = "frontend/.next"
